---
- name: Ssh port setting
  hosts: Ubuntu1
  become: true

  vars:
    new_port: 8822

  tasks:
    - name: Port change. New port is {{ new_port }}
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#Port*'
        line: 'Port {{ new_port }}'
        state: present

    - name: Reboot my servers
      shell: sleep 5 && shutdown -r now
      async: 1
      poll: 0

    - set_fact: ansible_ssh_port={{ new_port }}

    - name: Wait till my servers will come up online
      become: false
      wait_for:
        host: "{{ inventory_hostname }}"
        state: started
        delay: 5
        timeout: 60
      delegate_to: 127.0.0.1

    - ping:
