---
- name: Create user and append ssh-key
  hosts: ubuntu_servers
  become: true

  vars:
    spisok: "{{ lookup('file', './spisok.txt') }}"

  tasks:
    - name: create users
      user:
        name: "{{ item.key }}"
        password: $6$PSLmFNvkL3BgQi6N$wLQFQ0wP0N/WJpFPOPJGAFuv0njKumRW3slcgUA4/ygog0VMcLPXND1LuSEUe1hkFCAkabNI3LPvD.hbYjbAB1
        shell: /bin/bash
        groups: adm, cdrom, sudo, dip, plugdev, lxd
        append: true
      with_dict: "{{ spisok }}"

    - name:
      authorized_key:
        user: "{{ item.key }}"
        state: present
        key: "{{ item.value }}"
      with_dict: "{{ spisok }}"
