---
- name: Install Intel IPP
  hosts: Ubuntu1
  become: true

  vars:
    group: forecast
    user: user1  # lsger

  tasks:
    - name: Create directory for installer
      file:
        path: /intel
        state: directory
        mode: 0775
        owner: '{{ user }}'
        group: '{{ group }}'

    - name: Download installer
      get_url:
        dest: /intel
        url: https://pub.s3.iaaras.ru/l_ipp_oneapi_p_2021.8.0.46345_offline.sh
        # https://registrationcenter-download.intel.com/akdlm/IRC_NAS/7deeaac4-f605-4bcf-a81b-ea7531577c61/l_BaseKit_p_2023.1.0.46401_offline.sh
        # если хотим полную версию Intel OneApi
        # вся информация о новых версиях тут
        # https://www.intel.com/content/www/us/en/developer/tools/oneapi/toolkits.html#base-kit

    - name: Install Intel IPP
      shell: 'sh /intel/l_ipp_oneapi_p_2021.8.0.46345_offline.sh -a -s --eula accept'
      # /intel/l_BaseKit_p_2023.1.0.46401_offline.sh -a -s --eula accept
      ignore_errors: true
      register: results

    - debug:
        msg: "Intel IPP is already installed"
      when: '"It is already installed." in results.stdout'