---
- name: Create user and append ssh-key
  hosts: ubuntu_servers
  become: true

  vars:
    spisok: "{{ lookup('file', './spisok.txt') }}"
    group: forecast

  tasks:
    - name: Create group {{ group }}
      group:
        name: '{{ group }}'
        state: present

    - name: Check and create users
      include_tasks: auxiliary/playbook1_1check_user.yml
      with_dict: "{{ spisok }}"

    - name: add ssh-key
      authorized_key:
        user: "{{ item.key }}"
        state: present
        key: "{{ item.value }}"
      with_dict: "{{ spisok }}"
