---
 - name: Install apache and upload my web-page
   hosts: ubuntu_servers
   become: yes

   vars:
    source_file: ./my_web_site/
    destin_file: /var/www/html

   tasks:
   - name: Install apache web server
     apt: name=apache2 state=latest

   - name: Generate index.html file
     template: src={{ source_file }}/index.j2 dest={{ destin_file }}/index.html mode=0555
     notify: Restart apache

   - name: Copy my_home_page to servers
     copy: src={{ source_file }}/{{ item }} dest={{ destin_file }} mode=0555
     loop:
      - "1.png"
     notify: Restart apache

   - name: Start WevServers and make it enable on boot
     service: name=apache2 state=started enabled=yes

   handlers:
   - name: Restart apache
     service: name=apache2 state=restarted
