---
- name: Debag Tests!!!
  hosts: ubuntu_servers
  become: yes

  vars:
    massage1: hello


  tasks:
  - name: massage - {{ massage1 }}
    debug: var=ansible_distribution

  - debug: var=ansible_os_famely
