---
- name: Create users and append ssh-keys
  block:
    - name: Check user
      shell: cd /home/{{ item.key }}
      register: check_user
      ignore_errors: true

    - name: Create users
      user:
        name: "{{ item.key }}"
        password: "{{ 'zxcft67' | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo, forecast
        append: true
      when:  check_user.rc != 0